### PR TITLE
Improving appendix on Object-Oriented Programming

### PR DESCRIPTION
**Pull request by gusthoff**

### CODE REVIEW

**Review by sttaft — APPROVED** [review]
Looks good!

**Review by sttaft — COMMENTED** [review]
Looks good.  Only minor comment is grammatically it should be "in *the* case of procedures" rather than simply "in case of procedures."

**Review by sttaft — APPROVED** [review]
Looks good.

**Review by sttaft — DISMISSED** [review]
LGTM!

**Comment by gusthoff** [comment]
Thanks again, @sttaft,  for reviewing! I've just made that small grammar correction.

**Review by sttaft — APPROVED** [review]
LGTM

**Pull request merged**
