### PR TITLE
Various refinements

### PR DESCRIPTION
**Pull request by pat-rogers**
Change the title and motivation summary for the constructors idiom to say it is about ADTs, not just type extensions.
Refine the component access idiom to give example for immutably limited types, etc.

### CODE REVIEW

**Comment by gusthoff** [comment]
> Change the title and motivation summary for the constructors idiom to say it is about ADTs, not just type extensions. Refine the component access idiom to give example for immutably limited types, etc.

Since you're changing the chapter title, we should also rename the file (i.e. the actual .rst file for that chapter) accordingly. I'll take care of this separately later on.

**Review by gusthoff — APPROVED** [review]

**Comment by gusthoff** [comment]
Done: #1000

**Comment by gusthoff** [comment]
> Since you're changing the chapter title, we should also rename the file (i.e. the actual .rst file for that chapter) accordingly. I'll take care of this separately later on.

Done: #1000

**Comment by pat-rogers** [comment]
Thanks!

**Pull request merged**
