### PR TITLE
Use more complex example code on first page, with Run button too

### PR DESCRIPTION
**Pull request by yannickmoy**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Maybe a bit "cheesy" but I propose this:

```Ada
with Ada.Text_IO; use Ada.Text_IO;

procedure Main is
   
   subtype Alphabet is Character range 'A' .. 'Z';

begin

   Put_Line ("Learning Ada from " & Alphabet'First & " to " & Alphabet'Last);

end Main;
```

**Comment by yannickmoy** [comment]
feel free to push that other example, but then remove "Prove" button as there is nothing to prove in that snippet. And add run_button.

**Comment by Robert-Tice** [comment]
The example accesses Ada.Command_Line which the user can't utilize anyway with the infrastructure so I think I like @Fabien-Chouteau example.

**Comment by raph-amiard** [comment]
Fabien can you take care of it ?

**Comment by raph-amiard** [comment]
@Fabien-Chouteau can you take care of it ?

**Pull request merged**
